### PR TITLE
Feature/pull request trigger

### PR DESCRIPTION
**Pull request by joppa27**
add support to the github-sqs-plugin that allows it to process pull_request events, in addition to push events.

based off of:
https://github.com/jenkinsci/github-sqs-plugin/pull/9
https://github.com/jenkinsci/github-sqs-plugin/pull/10

### CODE REVIEW

**Comment by jaybocc2** [comment]
@aaronwalker have you given up maintaining this plugin?

**Comment by nemo83** [comment]
Hi @jaybocc2,

I've interest in becoming a maintainer for this plugin, how can I do that?

Thanks,
Gio

**Comment by jaybocc2** [comment]
@nemo83 probably want to email jenkinsci-users@googlegroups.com and see if they can help

**Comment by aaronwalker** [comment]
@joppa27 @nemo83  apologies for the delay I will review this PR in the next couple of days and merge it in. Also happy to make others admin on this repo if there is interest

**Comment by jaybocc2** [comment]
@aaronwalker did you ever get around to reviewing this? Also @nemo83 expressed interest in becoming a maintainer.

**Comment by aaronwalker** [comment]
added @nemo83 as a admin on this repo

**Comment by joppa27** [comment]
@aaronwalker @nemo83 need anything else from me on this PR?

**Comment by nemo83** [comment]
Hi,

just found out I've become admin of the repo. I'll take a quick look at this tomorrow. 

Apologies for the delay, looking forward to see this plugin to progress.

**Comment by jaybocc2** [comment]
@nemo83 `Only those with write access to this repository can merge pull requests.` as an admin you should certainly be able to merge, but you could always do a local merge and push via CLI.

**Comment by aaronwalker** [comment]
@nemo83 you need to accept the invite before you become an admin. I can see invite is still pending

**Comment by nemo83** [comment]
doh! Didn't see the invite. thanks @aaronwalker it's all good now.

**Pull request merged**
