### PR TITLE
Code Improvements

### PR DESCRIPTION
**Pull request by darxriggs**
Each commit covers a different aspect. Therefore reviewing this pull request commit by commit is suggested.

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @joppa27, @nemo83, @sethp-nr, as some time already passed since this pull-request was created, I just wanted to check if it can be merged?

**Comment by sethp-nr** [comment]
These changes look good to me, but I regret to inform you that I have no power to merge them.

**Review by nemo83 — APPROVED** [review]
🍾

**Comment by nemo83** [comment]
Thanks for the contribution. Will merge. Apologies for the delay. Will chase someone to make a new release.

**Comment by nemo83** [comment]
@aaronwalker any chance you can cut a new release with the latest changes? Thanks

**Comment by aaronwalker** [comment]
@nemo83 give me a day or so.. and @darxriggs thanks for contribution

**Pull request merged**
