### PR TITLE
Updated plugin so to use github trigger rather than custom trigger.

### PR DESCRIPTION
**Pull request by nemo83**
This version uses the github trigger rather then the custom one.

### CODE REVIEW

**Comment by errnoh** [comment]
Would be nice to get this merged at some point. Current plugin doesn't work with pipelines.

**Comment by errnoh** [comment]
Apparently this still doesn't solve the incompatibility with pipelines

**Comment by nemo83** [comment]
There are a number of prerequisites in order to see a build triggered:
* it has to be a github project
* SNS or SQS has to be correctly configured (I would recommend using SNS and bind a notification to your email address)
* It must be a **NEW** commit and not re-sending a previous sha (or commit, this in particular fooled me a couple of times when testing!!)

In case you still cannot see builds being triggered I'd appreciate more details on the issue and I'll try to look into it.

**Comment by errnoh** [comment]
It's not actually even the trigger that's the problem, it's that the `Build when a message is published to an SQS Queue` option is completely missing in Build Triggers section of job configuration on both Pipeline and Multibranch Pipeline projects.

**Comment by nemo83** [comment]
It's not required anymore. 

I think you will only have tick the option: `Build when a change is pushed to GitHub`

**Comment by errnoh** [comment]
Ok, I did some testing.
I created three project, one as a Freestyle project, one Pipeline and one Multibranch pipeline:

Freestyle project is using `Source Code Management` as `git` and `Build when a change is pushed to GitHub`. This triggers as it should with the SNS. (Worth noting, that there's the option for SQS Queue trigger, which doesn't do anything anymore when using this commit)

Pipeline has `Build triggers -> Build when a change is pushed to GitHub` enabled, the scm is specified under the `Pipeline -> Pipeline script from SCM -> Git`. This doesn't seem to do anything.

Multibranch Pipeline has `Branch sources -> Git` set, but the Build Triggers section only has options for `Build periodically` and `Periodically if not otherwise run`, no Github trigger on the list. `Multibranch Pipeline -> master -> View configuration` has `Build when a change is pushed to GitHub` trigger listed, but the configuration seems to be view only so it can't be enabled.

So it seems that the SNS only works in Freestyle project atm. Worth noting is, that Jenkins version I'm using is the latest stable: 2.7.2.

**Comment by nemo83** [comment]
Thanks for the details,

I'll take a look and let you know!

**Comment by errnoh** [comment]
@nemo83 Have you had time to look into this?

**Comment by nemo83** [comment]
Hi @errnoh ,

Sorry for the delay. I've done some testing today and I've just realised that for both `Pipeline` and `Multibranch Pipeline` you can't see the `Build when a change is pushed to GitHub`. I think this suggests that maybe the plugin is not correctly installed.

I would recommend uninstalling the previous/old one first and then:
* git clone https://github.com/nemo83/github-sqs-plugin.git
* cd github-sqs-plugin
* git checkout GithubSqsLight
* mvn package
* install the plugin from `Manage Jenkins` > `Manage Plugins` > `Advanced` > `Upload Plugin` > `choose file` -> go into the target folder and select `github-sqs-plugin.hpi`

Once installed and restarted you should see that the version of the plugin is something like `1.6-SNAPSHOT (private-9d592bbb-giovanni)`

**Comment by errnoh** [comment]
@nemo83 Hmm, I had some time to test this again. 

Previously I had installed the plugin by adding it under the plugins directory, it was showing up fine on the installed plugins list though. Just to be sure I reinstalled it now using the method you described above.

The reason why Pipeline project wasn't working might be the same one you had, that the build needed to start manually once before it starts to work. Anyways now it seems to work which is great.

I still can't figure out how to get Multibranch Pipeline working though. There's still no `Build when a change is pushed to GitHub` option on the https://example.com/job/jenkins-test/configure page. There is one on https://example.com/job/jenkins-test/job/master/configure page though, but as I mentioned above that page is view only and can't be changed.

The project configuration page only has triggers for `Build periodically` and `Periodically if not otherwise run`.

**Comment by nemo83** [comment]
Hi,

I don't think you need to configure anything in the `Multibranch` type of job in order to make it to work. Have you tried to just commit and push a **new revision**?

**Comment by errnoh** [comment]
Yeah, I've tried with multiple commits, different branches, etc. And I have three projects with the same hook (normal, pipeline and multibranch pipeline) and the others are being built fine, only multibranch pipeline doesn't start a build on commit.

I've attached screenshot of the configuration page. (Btw, I think I mentioned before, but clicking `Branch Indexing -> Run now` refreshes all branches and builds those with new commits, so that part is working)

multibranch

**Comment by ramyaa** [comment]
so, this does work on multibranch pipeline?

**Comment by gytisgreitai** [comment]
I can confirm that this works on Free Style and Pipeline projects. Would be nice to get it merged

**Comment by gytisgreitai** [comment]
And as @errnoh stated, it does not seem to work with Multibranch workflow.

**Comment by joppa27** [comment]
@aaronwalker @nemo83 @ramyaa @gytisgreitai I can confirm that this branch works!!
I have used it to read from SQS and trigger builds on jenkins containers running behind our firewall in both AWS and my local-machine!
```

**Comment by joppa27** [comment]
This was the Jenkinsfile I used for the multi-branch repo
```
pipeline {
    agent any
    triggers {
        githubPush()
    }

    stages {
       stage('do something') {
          steps {
             echo 'hello'
          }
        }
    }
}
```

**Pull request merged**
